version: '3.3'

services:

  web:
    container_name: template
    build:
      context: .
    links:
      - mysql
    networks:
      - servers
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=sdk_template
      - MYSQL_USER=sdk_template
      - MYSQL_PASSWORD=secret
    networks:
      - servers

networks:
  servers:
    external: true
