version: '3.7'

services:

  web:
    build:
      context: ./docker
    links:
      - mysql
    networks:
      - servers
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app
      - ./../../templates:/templates
      - ./../../sdk/base:/base
      - ./../../sdk/blog:/blog
    ports:
        - 8080:80
    secrets:
      - host_ssh_key

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=sdk_template
      - MYSQL_USER=sdk_template
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_HOST=%
    networks:
      - servers
    volumes:
        - db-mysql:/var/lib/mysql
secrets:
  host_ssh_key:
    file: ~/.ssh/id_rsa
networks:
  servers:
    external: true
volumes:
  db-mysql:
