version: '3.7'

services:

  web:
    container_name: server
    build:
      context: ./docker
    links:
      - mysql
    networks:
      - servers
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app
      - /home/hellsythe/projects/templates:/templates
      - /home/hellsythe/projects/sdk:/sdk
    ports:
        - 80:80

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=sdk_template
      - MYSQL_USER=sdk_template
      - MYSQL_PASSWORD=secret
    networks:
      - servers

networks:
  servers:
    external: true
